"""add stock to food item

Revision ID: 5d717db219d2
Revises: bd649bd3d0b1
Create Date: 2026-09-29 01:30:05.871284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d717db219d2'
down_revision: Union[str, Sequence[str], None] = 'bd649bd3d0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('stock', sa.Integer(), server_default='0', nullable=False))
    op.create_check_constraint('ck_food_items_stock_non_negative', 'food_items', 'stock >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_food_items_stock_non_negative', 'food_items', type_='check')
    op.drop_column('food_items', 'stock')
    # ### end Alembic commands ###
