"""Add price check constraint

Revision ID: 83cda8b85131
Revises: 72bb01cbb9f8
Create Date: 2026-09-26 01:05:37.425965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83cda8b85131'
down_revision: Union[str, Sequence[str], None] = '72bb01cbb9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_food_items_price_non_negative', 'food_items', 'price >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_food_items_price_non_negative', 'food_items', type_='check')
    # ### end Alembic commands ###
